import {
  EduKito,
  Eduvibe,
  EduWell,
  RedOnion,
  PatoRes,
  CreativeAgency,
  CreativeAgency2,
  CreativeAgency3,
  CreativeAgency4,
  EduKito2,
  EduKito3,
  EduKito4,
  Eduvibe2,
  Eduvibe3,
  Eduvibe4,
  RedOnion2,
  RedOnion3,
  RedOnion4,
  PatoRes2,
  PatoRes3,
  PatoRes4,
  Promptopia,
  Promptopia2,
  Promptopia3,
  Promptopia4,
  threads,
  threads2,
  threads3,
  threads4,
  ecommerce1,
  ecommerce2,
  ecommerce3,
  ecommerce4,
  ecommerce5,
  ecommerce6,
  even2,
  even3,
  even1,
} from "../assets/img";

export const ProjectsList1 = [
  {
    id: 1,
    title: "EduVibe",
    description: "Design & Development",
    imgUrl: Eduvibe,
    link: "https://eduwave-murex.vercel.app/home",
    images: [Eduvibe, Eduvibe2, Eduvibe3],
    gitHubLink: "https://github.com/BhanuPrakash7297/eduwave-frontend",
    projDes: [
      "Users can create an account, log in, and enroll in courses.",
      "The website features a dashboard where users can manage their courses",
      "Private routing for authenticated users is implemented using React Router.",
      "Firebase handles user authentication.",
      "The application leverages the MERN stack for efficient development and deployment",
      "The website has a clean and modern user interface for optimal user experience.",
    ],
    technology: [
      "React.js",
      "react-router-dom",
      "react-hook-form",
      "AOS",
      "Bootstrap",
      "stripe",
      "react-query",
      "axios",
      "date-fns",
      "firebase",
      "vercel",
      "Express.js",
      "react-hot-toast",
      "react-icons",
      "typewriter-effect",
    ],
  },
  {
    id: 2,
    title: "ShopCart",
    description: "Design & Development",
    imgUrl: ecommerce1,
    link: "https://testing-8gyd.vercel.app/Home",
    images: [
      ecommerce1,
      ecommerce2,
      ecommerce3,
      ecommerce4,
      ecommerce5,
      ecommerce6,
    ],
    gitHubLink: "https://github.com/BhanuPrakash7297/Ecommerce-frontend",
    projDes: [
      "User can select different categories for product",
      "User can select quantity and add the product to the cart",
      "Users can create an account, log in, and order for product",
      "The website features a dashboard where users can manage their Order",
      "Private routing for authenticated users is implemented using React Router.",
      "jwt is used for authentication.",
      "The application leverages the MERN stack for efficient development and deployment",
      "The website has a clean and modern user interface for optimal user experience.",
    ],
    technology: [
      "React.js",
      "react-router-dom",
      "react-hook-form",
      "AOS",
      "Bootstrap",
      "react-query",
      "axios",
      "date-fns",
      "firebase",
      "vercel",
      "Express.js",
      "react-hot-toast",
      "react-icons",
      "typewriter-effect",
    ],
  },

  {
    id: 3,
    title: "Evently",
    description: "Design & Development",
    imgUrl: even1,
    link: "https://evently-web-five.vercel.app/",
    images: [even1, even2, even3],
    gitHubLink: "https://github.com/BhanuPrakash7297/Evently_Web",
    projDes: [
      "User Authentication: Utilizes Clerk for secure user authentication and login.",
      "Create Events. application allows user to create events and also to participate in others",
      "Event Search: Easily find and join Events",
      "Mobile Responsive: The website is designed to be responsive and accessible on mobile devices.",
    ],
    technology: [
      "next.13",
      "next-router",
      "react-hook-form",
      "svix",
      "tailwind Css",
      "clerk",
      "nodejs",
      "axios",
      "mongodb  ",
      "typescript",
      "vercel",
      "Express.js",
      "zod",
      "react-icons",
    ],
  },
];
